import Head from "next/head";
import FeedCard from "@/components/FeedCard";
import MainNavbar from "@/components/MainNavbar";
import { Button, Container, Navbar, Text, Spacer } from "@nextui-org/react";

export default function Feed() {
  return (
    <>
      <Head>
        <title>Your Feed | NeighborNet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <MainNavbar currentPage="feed" />
          <Container xs>
            <Spacer y={2} />
            <FeedCard />
            <Spacer y={1} />
            <FeedCard />
            <Spacer y={1} />
            <FeedCard />
            <Spacer y={1} />
            <FeedCard />
          </Container>
        </div>
      </main>
    </>
  );
}
