import Head from "next/head";
import IncidentCard from "@/components/IncidentCard";
import MainNavbar from "@/components/MainNavbar";
import { Button, Container, Navbar, Text, Spacer } from "@nextui-org/react";

export default function Feed() {
  return (
    <>
      <Head>
        <title>Incidents | NeighborNet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <MainNavbar currentPage="incidents" />
          <Container xs>
            <Spacer y={2} />
            <IncidentCard />
            <Spacer y={1} />
            <IncidentCard />
            <Spacer y={1} />
            <IncidentCard />
            <Spacer y={1} />
            <IncidentCard />
          </Container>
        </div>
      </main>
    </>
  );
}
