import Head from "next/head";
import IncidentCard from "@/components/IncidentCard";
import MainNavbar from "@/components/MainNavbar";
import {
  Textarea,
  Input,
  Container,
  Text,
  Spacer,
  Button,
  Modal,
} from "@nextui-org/react";
import { useState, useEffect } from "react";
import { auth, firestore } from "@/firebase";
import { useAuthState } from "react-firebase-hooks/auth";

export default function Incidents() {
  // For Popup
  const [visible, setVisible] = useState(false);
  const handler = () => setVisible(true);
  const closeHandler = () => {
    setVisible(false);
    console.log("closed");
  };

  const [user] = useAuthState(auth);

  return (
    <>
      <Head>
        <title>Incidents | NeighborNet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <Container gap={28}>
            <Spacer y={1} />
            <Text h1>Recent Incidents</Text>
            {user ? (
              <Button auto color="primary" onPress={handler}>
                {" "}
                Report Incident{" "}
              </Button>
            ) : (
              <></>
            )}

            <Modal
              closeButton
              blur
              aria-labelledby="modal-title"
              open={visible}
              onClose={closeHandler}
            >
              <Modal.Header>
                <Text id="modal-title" size={18}>
                  {" "}
                  Create Incident Report{" "}
                </Text>
              </Modal.Header>

              <Modal.Body>
                <Input bordered color="primary" fullWidth placeholder="Title" />
                <Textarea bordered color="primary" placeholder="Description" />
                <Input
                  bordered
                  color="primary"
                  fullWidth
                  placeholder="Location"
                />
                <Input bordered fullWidth label="Time" type="time" />
                <Input bordered label="Date" type="date" />
              </Modal.Body>
            </Modal>

            <Spacer y={1} />
            <IncidentCard />
            <Spacer y={1} />
            <IncidentCard />
            <Spacer y={1} />
            <IncidentCard />
            <Spacer y={1} />
            <IncidentCard />
          </Container>
        </div>
      </main>
    </>
  );
}
