import Head from 'next/head'
import { Button } from '@nextui-org/react';

const Component = () => <Button>Click me</Button>;


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <Component />
        </div>
      </main>
    </>
  )
}
