import Head from "next/head";
import React from "react";
import MainNavbar from "@/components/MainNavbar";
import {
  useInput,
  Button,
  Input,
  Container,
  Row,
  Text,
  Spacer,
} from "@nextui-org/react";
import { MdLockOutline, MdLockOpen } from "react-icons/md";

export default function Feed() {
  const { value, reset, bindings } = useInput("");
  const validateEmail = (value: string) => {
    return value.match(/^[A-Z0-9._%+-]+@[A-Z0-9.-]+.[A-Z]{2,4}$/i);
  };
  const helper = React.useMemo(() => {
    if (!value) return { text: "" };
    const isValid = validateEmail(value);
    return { text: isValid ? "Valid Email" : "Enter a valid email" };
  }, [value]);
  return (
    <>
      <Head>
        <title>Setup | NeighborNet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <MainNavbar currentPage="setup" />
          <Container xs>
            <Spacer y={2} />
            <Row justify="center">
              <Text h1>Create Account</Text>
            </Row>
            <Spacer y={1} />
            <Input bordered fullWidth label="Name" placeholder="Name" />
            <Spacer y={1.6} />
            <Input
              {...bindings}
              bordered
              shadow={false}
              onClearClick={reset}
              helperText={helper.text}
              type="email"
              label="Email"
              fullWidth
              placeholder="Email"
            />
            <Spacer y={1.6} />
            <Input.Password
              bordered
              label="Password"
              fullWidth
              placeholder="Password"
              visibleIcon={<MdLockOpen fill="currentColor" />}
              hiddenIcon={<MdLockOutline fill="currentColor" />}
            />
            <Spacer y={1.7} />
            <Row justify="center">
              <Button>Sign Up</Button>
            </Row>
          </Container>
        </div>
      </main>
    </>
  );
}
